//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grad_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer_tbl
    {
        public string Ans_ID { get; set; }
        public string Exam_ID { get; set; }
        public string Stu_Code { get; set; }
        public string Ans_1 { get; set; }
        public string Ans_2 { get; set; }
        public string Ans_3 { get; set; }
        public string Ans_4 { get; set; }
        public string Ans_5 { get; set; }
        public string Ans_6 { get; set; }
        public string Ans_7 { get; set; }
        public string Ans_8 { get; set; }
        public string Ans_9 { get; set; }
        public string Ans_10 { get; set; }
    }
}
