//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grad_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event_tbl
    {
        public string ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public string Type { get; set; }
        public Nullable<int> Ed_Level { get; set; }
        public string CourseID { get; set; }
    
        public virtual Course_tbl Course_tbl { get; set; }
    }
}
