//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grad_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class File_tbl
    {
        public int ID { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> UploadOn { get; set; }
        public byte[] File { get; set; }
        public string CourseID { get; set; }
    
        public virtual Course_tbl Course_tbl { get; set; }
    }
}
