//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grad_Project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LMSDBEntities : DbContext
    {
        public LMSDBEntities()
            : base("name=LMSDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin_tbl> Admin_tbl { get; set; }
        public virtual DbSet<Attendance_tbl> Attendance_tbl { get; set; }
        public virtual DbSet<Course_tbl> Course_tbl { get; set; }
        public virtual DbSet<Event_tbl> Event_tbl { get; set; }
        public virtual DbSet<Lecturer_tbl> Lecturer_tbl { get; set; }
        public virtual DbSet<RegisteredCourses_tbl> RegisteredCourses_tbl { get; set; }
        public virtual DbSet<Result_tbl> Result_tbl { get; set; }
        public virtual DbSet<Student_tbl> Student_tbl { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<File_tbl> File_tbl { get; set; }
    }
}
