//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grad_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Question_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question_tbl()
        {
            this.Exam_tbl = new HashSet<Exam_tbl>();
            this.Exam_tbl1 = new HashSet<Exam_tbl>();
            this.Exam_tbl2 = new HashSet<Exam_tbl>();
            this.Exam_tbl3 = new HashSet<Exam_tbl>();
            this.Exam_tbl4 = new HashSet<Exam_tbl>();
            this.Exam_tbl5 = new HashSet<Exam_tbl>();
            this.Exam_tbl6 = new HashSet<Exam_tbl>();
            this.Exam_tbl7 = new HashSet<Exam_tbl>();
            this.Exam_tbl8 = new HashSet<Exam_tbl>();
            this.Exam_tbl9 = new HashSet<Exam_tbl>();
        }
        [Display(Name = "Question ID")]
        public string Q_ID { get; set; }
        public string Ch01 { get; set; }
        public string Ch02 { get; set; }
        public string Ch03 { get; set; }
        public string Ch04 { get; set; }
        [Display(Name = "Correct Answer")]
        public string Correct_Ch { get; set; }
        public Nullable<bool> IsCorrect { get; set; }
        [Display(Name = "Total Mark")]
        public Nullable<int> Total_Mark { get; set; }
        [Display(Name = "Achieved Mark")]
        public Nullable<int> Achieved_Mark { get; set; }
        [Display(Name = "Question")]
        public string Ques_Title { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exam_tbl> Exam_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exam_tbl> Exam_tbl1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exam_tbl> Exam_tbl2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exam_tbl> Exam_tbl3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exam_tbl> Exam_tbl4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exam_tbl> Exam_tbl5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exam_tbl> Exam_tbl6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exam_tbl> Exam_tbl7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exam_tbl> Exam_tbl8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exam_tbl> Exam_tbl9 { get; set; }
    }
}
