//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grad_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student_tbl()
        {
            this.Attendance_tbl = new HashSet<Attendance_tbl>();
            this.Result_tbl = new HashSet<Result_tbl>();
        }
    
        public string ID { get; set; }
        [Display(Name = "Student Name")]
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public byte[] Salt { get; set; }
        public string Department { get; set; }
        [Display(Name = "Level")]
        public int Ed_Level { get; set; }
        public byte[] Image { get; set; }
        public string Attend_Courses { get; set; }
        public string Registered_Courses { get; set; }
        public string Results { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance_tbl> Attendance_tbl { get; set; }
        public virtual Attendance_tbl Attendance_tbl1 { get; set; }
        public virtual RegisteredCourses_tbl RegisteredCourses_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Result_tbl> Result_tbl { get; set; }
        public virtual Result_tbl Result_tbl1 { get; set; }
    }
}
